In [ ]:
!apt-get update -qq
!apt-get install -y r-base

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  r-base-core r-recommended
Suggested packages:
  elpa-ess r-doc-info | r-doc-pdf r-mathlib r-base-html
Recommended packages:
  r-base-html r-doc-html
The following packages will be upgraded:
  r-base r-base-core r-recommended
3 upgraded, 0 newly installed, 0 to remove and 134 not upgraded.
Need to get 30.3 MB of archives.
After this operation, 30.7 kB of additional disk space will be used.
Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ r-base-core 4.6.1-1.2204.1 [30.3 MB]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ r-base 4.6.1-1.2204.1 [48.1 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ r-r

Vector Addition

In [ ]:
# Load R magic
%load_ext rpy2.ipython

In [ ]:
# Install rpy2
!pip install -q rpy2

In [ ]:
%%R

c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15


In [ ]:
%%R

c(2,3,5,7) + c(8,9)

[1] 10 12 13 16


In [ ]:
%%R

c(2,3,5,7) + c(8,9,11)

[1] 10 12 16 15


In addition: Warning message:
In c(2, 3, 5, 7) + c(8, 9, 11) :
  longer object length is not a multiple of shorter object length


In [ ]:
%%R

c(2,3,5,7) + c(8)

[1] 10 11 13 15


In [ ]:
%%R

c(2,3,5,7) + 8

[1] 10 11 13 15


Vector Subtraction

In [ ]:
%%R

c(2,3,5,7) - c(-2,-3,-5,8)

[1]  4  6 10 -1


In [ ]:
%%R

c(2,3,5,7) - c(8,9)

[1] -6 -6 -3 -2


In [ ]:
%%R

c(2,3,5,7) - c(8)

[1] -6 -5 -3 -1


In [ ]:
%%R

c(2,3,5,7) - 8

[1] -6 -5 -3 -1


Vector Multiplication

In [ ]:
%%R

c(2,3,5,7) * c(-2,-3,-5,8)

[1]  -4  -9 -25  56


In [ ]:
%%R

c(2,3,5,7) * c(8,9)

[1] 16 27 40 63


In [ ]:
%%R

c(2,3,5,7) * c(8)

[1] 16 24 40 56


In [ ]:
%%R

c(2,3,5,7) * 8

[1] 16 24 40 56


Vector Division

In [ ]:
%%R

c(2,3,5,7) / c(-2,-3,-5,8)

[1] -1.000 -1.000 -1.000  0.875


In [ ]:
%%R

c(2,3,5,7) / c(8,9)

[1] 0.2500000 0.3333333 0.6250000 0.7777778


In [ ]:
%%R

c(2,3,5,7) / c(8)

[1] 0.250 0.375 0.625 0.875


In [ ]:
%%R

c(2,3,5,7) / 8

[1] 0.250 0.375 0.625 0.875


Scalar Arithmetic

In [ ]:
%%R

2 + 5

[1] 7


In [ ]:
%%R

2 - 5

[1] -3


In [ ]:
%%R

2 * 5

[1] 10


In [ ]:
%%R

2 / 5

[1] 0.4


Assignment

In [ ]:
%%R

x <- 5
x

[1] 5


In [ ]:
%%R

x = 5
x

[1] 5


In [ ]:
%%R

a <- 10
b <- 20

a
b

[1] 20


In [ ]:
%%R

x <- c(2,4,6,8)
x

[1] 2 4 6 8


Numeric Variable

In [ ]:
%%R

num <- 25
num

[1] 25


In [ ]:
%%R

class(num)

[1] "numeric"


Character Variable

In [ ]:
%%R

name <- "R Programming"
name

[1] "R Programming"


In [ ]:
%%R

class(name)

[1] "character"


Logical Variable

In [ ]:
%%R

flag <- TRUE
flag

[1] TRUE


In [ ]:
%%R

class(flag)

[1] "logical"


Integer Variable

In [ ]:
%%R

class(num)

[1] "integer"


In [ ]:
%%R

num <- 25L
num

[1] 25


Checking Numeric Values

In [ ]:
%%R

is.numeric(25)

[1] TRUE


In [ ]:
%%R

is.numeric("25")

[1] FALSE


In [ ]:
%%R

is.numeric(c(2,3,4))

[1] TRUE


In [ ]:
%%R

is.numeric(c("A","B","C"))

[1] FALSE


Checking Character Values

In [ ]:
%%R

is.character("Hello")

[1] TRUE


In [ ]:
%%R

is.character(123)

[1] FALSE


In [ ]:
%%R

is.character(c("A","B","C"))

[1] TRUE


In [ ]:
%%R

is.character(c(1,2,3))

[1] FALSE


Character to Numeric

In [ ]:
%%R

x <- c("10","20","30")

as.numeric(x)

[1] 10 20 30


In [ ]:
%%R

x <- "25"

as.numeric(x)

[1] 25


In [ ]:
%%R

x <- c("10","ABC","30")

as.numeric(x)

[1] 10 NA 30


In addition: Warning message:
In (function (expr, envir = parent.frame(), enclos = if (is.list(envir) ||  :
  NAs introduced by coercion


Numeric to Character

In [ ]:
%%R

x <- 25

as.character(x)

[1] "25"


In [ ]:
%%R

x <- c(10,20,30)

as.character(x)

[1] "10" "20" "30"


Comments

In [ ]:
%%R

# This is a comment

5 + 10

[1] 15


In [ ]:
%%R

x <- 50      # Store value
y <- 100     # Store another value

x + y

[1] 150


Case sensitivity

In [ ]:
%%R

x <- 100
X <- 200

x
X

[1] 200


In [ ]:
%%R

apple <- 10
Apple <- 20

apple
Apple

[1] 20


Printing Variables

In [ ]:
%%R

x <- 15

print(x)

[1] 15


In [ ]:
%%R

name <- "R Language"

print(name)

[1] "R Language"


Removing Variables

In [ ]:
%%R

x <- 10

rm(x)

In [ ]:
%%R

ls()

[1] "a"     "apple" "Apple" "b"     "flag"  "name"  "num"   "X"     "y"    


mode()

In [ ]:
%%R

x <- 25
mode(x)

[1] "numeric"


In [ ]:
%%R

x <- "R Programming"
mode(x)

[1] "character"


In [ ]:
%%R

x <- TRUE
mode(x)

[1] "logical"


In [ ]:
%%R

x <- c(2,4,6,8)
mode(x)

[1] "numeric"


storage.mode()

In [ ]:
%%R

x <- 25
storage.mode(x)

[1] "double"


In [ ]:
%%R

x <- "Hello"
storage.mode(x)

[1] "character"


In [ ]:
%%R

x <- TRUE
storage.mode(x)

[1] "logical"


In [ ]:
%%R

x <- c(10,20,30)
storage.mode(x)

[1] "double"


typeof()

In [ ]:
%%R

x <- 25
typeof(x)

[1] "double"


In [ ]:
%%R

x <- "ABC"
typeof(x)

[1] "character"


In [ ]:
%%R

x <- TRUE
typeof(x)

[1] "logical"


In [ ]:
%%R

x <- c(1,2,3)
typeof(x)

[1] "double"


Length

In [ ]:
%%R

x <- c(2,4,6,8)

length(x)

[1] 4


In [ ]:
%%R

x <- c("A","B","C","D","E")

length(x)

[1] 5


In [ ]:
%%R

length(100)

[1] 1


Infinity()

In [ ]:
%%R

10/0

[1] Inf


In [ ]:
%%R

-10/0

[1] -Inf


In [ ]:
%%R

Inf

[1] Inf


In [ ]:
%%R

is.infinite(Inf)

[1] TRUE


In [ ]:
%%R

is.infinite(100)

[1] FALSE


R as a calculator

In [84]:
2 * 3 - 4 + 5 / 6

2.8333333333333335

In [85]:
# Command for BODMAS
(2 + 3) * 5 + 5 - 10

20

In [86]:
# Command for BODMAS
(((2 + 3) * 5 + 5) - 10) / 2

10.0

In [89]:
%%R

# Addition of scalar with vector
c(2,3,5,7) + 10

[1] 12 13 15 17


In [91]:
%%R
# Subtraction of scalar with vector
c(12,13,15,17) - 10


[1] 2 3 5 7


In [93]:
%%R
# Multiplication of scalar with vector
c(2,3,5,7) * 10

[1] 20 30 50 70


In [95]:
%%R
# Division of scalar with vector
c(12,13,15,17) / 10

[1] 1.2 1.3 1.5 1.7


Week 3

In [96]:
%%R
# Power operations
2^3
2**3
2^0.5
2**0.5
2^-0.5

[1] 0.7071068


In [97]:
%%R
c(2,3,5,7)^2

[1]  4  9 25 49


In [98]:
%%R
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343


In [99]:
%%R
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296


In [100]:
%%R
c(2,3,5,7)^c(2,3,4)

[1]   4  27 625  49


In addition: Warning message:
In c(2, 3, 5, 7)^c(2, 3, 4) :
  longer object length is not a multiple of shorter object length


In [101]:
%%R
# Integer division
2 %/% 2
5 %/% 2
7 %/% 3

[1] 2


In [102]:
%%R
c(2,3,5,7) %/% 2

[1] 1 1 2 3


In [103]:
%%R
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2


In [104]:
%%R
c(2,3,5) %/% c(2,3)

[1] 1 1 2


In addition: Warning message:
In c(2, 3, 5)%/%c(2, 3) :
  longer object length is not a multiple of shorter object length


In [105]:
%%R
# Modulo division
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 3


In [106]:
%%R
c(2,3,5,7) %% 2

[1] 0 1 1 1


In [107]:
%%R
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1


In [108]:
%%R
c(2,3,5) %% c(2,3)

[1] 0 0 1


In addition: Warning message:
In c(2, 3, 5)%%c(2, 3) :
  longer object length is not a multiple of shorter object length


In [109]:
%%R
# Max and Min
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] -7.8


In [110]:
%%R
# Mean
mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 3


In [111]:
%%R
# abs and sqrt
abs(-4)
abs(c(-1,-2,-3,4,5))
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2 3 4 5


In [112]:
%%R
# sum and prod
sum(c(2,3,5,7))
prod(c(2,3,5,7))

[1] 210


In [113]:
%%R
# round
round(1.23)
round(1.83)

[1] 2


In [114]:
%%R
# log functions
log(10)
log(exp(1))
log(c(10, 100, 1000))
log10(10)
log10(100)
log10(c(10, 100, 1000))

[1] 1 2 3


In [115]:
%%R
# Assignments
x1 = c(1,2,3,4)
x1
x2 = x1^2
x2

[1]  1  4  9 16


In [116]:
%%R
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))
abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)))

[1] 19 18 17 16


In [117]:
%%R
# Matrix - default column-wise fill
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


In [118]:
%%R
# Access single element
x[3,2]

[1] 7


In [119]:
%%R
# Matrix - explicit byrow = FALSE
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = FALSE)
x

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


In [120]:
%%R
# Matrix - byrow = TRUE
y = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = TRUE)
y

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8


In [121]:
%%R
# Matrix properties
dim(x)
nrow(x)
ncol(x)
mode(x)
attributes(x)

$dim
[1] 4 2

